In [1]:
import numpy as np

# Create a dataset
X = np.array([[i] for i in range(1, 11)])
y = np.array([i for i in range(1, 11)])


In [2]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [3]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5)

# Splitting the dataset into 5 folds
folds = list(kf.split(X))


In [5]:
folds

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [6]:

for fold_idx, (train_index, test_index) in enumerate(folds):
    print(f"Fold {fold_idx + 1}")
    print(f"Train indices: {train_index}")
    print(f"Test indices: {test_index}")
    print()

Fold 1
Train indices: [2 3 4 5 6 7 8 9]
Test indices: [0 1]

Fold 2
Train indices: [0 1 4 5 6 7 8 9]
Test indices: [2 3]

Fold 3
Train indices: [0 1 2 3 6 7 8 9]
Test indices: [4 5]

Fold 4
Train indices: [0 1 2 3 4 5 8 9]
Test indices: [6 7]

Fold 5
Train indices: [0 1 2 3 4 5 6 7]
Test indices: [8 9]



In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Initialize the model
model = LinearRegression()

# Store the results of each fold
train_scores = []
test_scores = []

for fold_idx, (train_index, test_index) in enumerate(folds):
    # Split data into training and testing sets
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Predict on training and testing sets
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Calculate and store the scores
    train_score = mean_squared_error(y_train, y_train_pred)
    test_score = mean_squared_error(y_test, y_test_pred)
    train_scores.append(train_score)
    test_scores.append(test_score)
    
    print(f"Fold {fold_idx + 1}")
    print(f"Train MSE: {train_score}")
    print(f"Test MSE: {test_score}")
    print()

# Average scores
print(f"Average Train MSE: {np.mean(train_scores)}")
print(f"Average Test MSE: {np.mean(test_scores)}")

Fold 1
Train MSE: 5.17689969051289e-31
Test MSE: 4.0429121392576855e-30

Fold 2
Train MSE: 6.224605580259546e-31
Test MSE: 7.888609052210118e-31

Fold 3
Train MSE: 1.5284180038657104e-30
Test MSE: 3.944304526105059e-31

Fold 4
Train MSE: 1.232595164407831e-30
Test MSE: 3.1554436208840472e-30

Fold 5
Train MSE: 1.232595164407831e-30
Test MSE: 3.1554436208840472e-30

Average Train MSE: 1.0267517719517231e-30
Average Test MSE: 2.3074181477714594e-30
