In [1]:
import numpy as np;

In [38]:
def ImplementGradientDescent(x, y, iterations, a, b):
    m = len(x);
    lr = 0.001;
    for i in range(1):
        y_preds = a + b*x;
        error = y_preds - y;
        print(y_preds)
        cost = (1/(2*m)) * np.sum(error**2)
        error_a = np.sum(error)/m;
        error_b = np.sum(error*x)/m;
        a = a - lr*error_a;
        b = b - lr*error_b;
        # print(f"after {i}th value of a is {a} and value of b is {b} and cost is {cost}")

In [40]:
x = []
y = []
data_length = 5;
iterations = 10000;
for i in range(data_length):
    x.append(i)
    y.append(i*3 + 2);
ImplementGradientDescent(np.array(x, dtype="int64"), np.array(y, dtype="int64"), iterations, 0, 0);

[0 0 0 0 0]


In [30]:
nx = np.array(x)
ny = np.array(y)
nx, ny

(array([0, 1, 2, 3, 4]), array([ 2,  5,  8, 11, 14]))

array([0, 2, 4, 6, 8])

In [37]:
import numpy as np

def ImplementGradientDescent(x, y, iterations, a, b):
    m = len(x)
    lr = 0.001
    for i in range(iterations):
        # Calculate the predictions
        y_preds = a + b * x
        
        # Calculate the errors
        error = y_preds - y
        
        # Calculate the cost (mean squared error)
        cost = (1/(2*m)) * np.sum(error**2)
        
        # Calculate gradients
        error_a = np.sum(error) / m
        error_b = np.sum(error * x) / m
        
        # Update parameters
        a -= lr * error_a
        b -= lr * error_b
        
        # Optionally print error for monitoring
        if i % 1 == 0:  # Adjusted to print every iteration since there are only 10 iterations
            print(f"After {i} iterations: a = {a}, b = {b}, cost = {cost}")

    print(f"After {iterations} iterations: a = {a}, b = {b}")

if __name__ == "__main__":
    x = []
    y = []
    data_length = 5
    iterations = 10000
    for i in range(data_length):
        x.append(i)
        y.append(i * 3 + 2)
    
    print(x)
    print(y)
    
    ImplementGradientDescent(np.array(x, dtype="int64"), np.array(y, dtype="int64"), iterations, 0, 0)


[0, 1, 2, 3, 4]
[2, 5, 8, 11, 14]
After 0 iterations: a = 0.008, b = 0.022, cost = 41.0
After 1 iterations: a = 0.015947999999999997, b = 0.043851999999999995, cost = 40.453836
After 2 iterations: a = 0.023844347999999998, b = 0.065556992, cost = 39.914966866456
After 3 iterations: a = 0.031689389668, b = 0.08711596135199999, cost = 39.383295153528195
After 4 iterations: a = 0.039483468355628, b = 0.10852988680455199, cost = 38.85872471707879
After 5 iterations: a = 0.04722692511366327, b = 0.1297997405470134, cost = 38.34116069728353
After 6 iterations: a = 0.05492009870745558, b = 0.150926488253504, cost = 37.83050950147564
After 7 iterations: a = 0.06256332563224112, b = 0.17191108912656805, cost = 37.326678787218796
After 8 iterations: a = 0.07015694012835574, b = 0.19275449594054417, cost = 36.82957744560635
After 9 iterations: a = 0.0777012741963463, b = 0.2134576550846442, cost = 36.3391155847835
After 10 iterations: a = 0.08519665761198067, b = 0.23402150660574364, cost = 35.85

After 6974 iterations: a = 1.8947822832976966, b = 3.0369083821280873, cost = 0.0018563464214250052
After 6975 iterations: a = 1.8948136842501426, b = 3.0368973672687236, cost = 0.0018552385785749342
After 6976 iterations: a = 1.894845075831355, b = 3.036886355696611, cost = 0.001854131396870737
After 6977 iterations: a = 1.8948764580441304, b = 3.0368753474107684, cost = 0.0018530248759178589
After 6978 iterations: a = 1.8949078308912648, b = 3.0368643424102153, cost = 0.0018519190153219733
After 6979 iterations: a = 1.8949391943755531, b = 3.0368533406939715, cost = 0.0018508138146889606
After 6980 iterations: a = 1.8949705484997896, b = 3.0368423422610564, cost = 0.0018497092736249974
After 6981 iterations: a = 1.8950018932667678, b = 3.0368313471104904, cost = 0.0018486053917364448
After 6982 iterations: a = 1.8950332286792801, b = 3.036820355241294, cost = 0.0018475021686299034
After 6983 iterations: a = 1.8950645547401184, b = 3.0368093666524874, cost = 0.0018463996039122473
Afte